id: P009092
initial_creation_type: ocr
source_metadata:
  id: bdr:W2DB25436
  title: རོགས་འཐེན
  author: ''
  volumes:
    1840f46ec70b4a82b0ad7c369548f01a:
      image_group_id: I1PD36473
      title: ''
      volume_number: 1
      total_pages: 167
      base_file: v001.txt
